# Generated by Django 6.0.5 on 2026-05-24 16:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id_criptografado', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('ano', models.SmallIntegerField()),
                ('mes', models.SmallIntegerField()),
                ('data', models.DateField(blank=True, db_index=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('delito', models.IntegerField(blank=True, null=True)),
                ('desc_delito', models.CharField(db_index=True, max_length=120)),
                ('aisp', models.SmallIntegerField(blank=True, db_index=True, null=True)),
                ('risp', models.SmallIntegerField(blank=True, db_index=True, null=True)),
                ('locf', models.CharField(blank=True, max_length=255)),
                ('dia_semana', models.CharField(blank=True, max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'indexes': [models.Index(fields=['data', 'desc_delito'], name='ocorrencias_data_92e6e0_idx')],
            },
        ),
    ]
