# Generated by Django 6.0.5 on 2026-05-24 16:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id_ponto', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('nome_area_fm', models.CharField(db_index=True, max_length=120)),
                ('id_trecho', models.PositiveIntegerField(db_index=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'indexes': [models.Index(fields=['nome_area_fm', 'id_trecho'], name='ocorrencias_nome_ar_cc5dbe_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiskDenuncia',
            fields=[
                ('id_denuncia', models.IntegerField(primary_key=True, serialize=False)),
                ('numero_denuncia', models.CharField(db_index=True, max_length=30, unique=True)),
                ('data_denuncia', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('data_difusao', models.DateTimeField(blank=True, null=True)),
                ('timestamp_insercao', models.DateTimeField(blank=True, null=True)),
                ('tipo_logradouro', models.CharField(blank=True, max_length=10)),
                ('logradouro', models.CharField(blank=True, max_length=120)),
                ('numero_logradouro', models.CharField(blank=True, max_length=20)),
                ('complemento_logradouro', models.CharField(blank=True, max_length=120)),
                ('bairro_logradouro', models.CharField(blank=True, db_index=True, max_length=80)),
                ('subbairro_logradouro', models.CharField(blank=True, max_length=80)),
                ('cep_logradouro', models.CharField(blank=True, max_length=9)),
                ('referencia_logradouro', models.CharField(blank=True, max_length=255)),
                ('municipio', models.CharField(blank=True, max_length=80)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('xpto_id', models.IntegerField(blank=True, null=True)),
                ('xpto_nome', models.CharField(blank=True, max_length=80)),
                ('orgao_id', models.IntegerField(blank=True, null=True)),
                ('orgao_nome', models.CharField(blank=True, max_length=100)),
                ('orgao_tipo', models.CharField(blank=True, max_length=12)),
                ('id_classe', models.SmallIntegerField(blank=True, db_index=True, null=True)),
                ('classe', models.CharField(blank=True, db_index=True, max_length=100)),
                ('id_tipo', models.SmallIntegerField(blank=True, db_index=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('assunto_principal', models.BooleanField(blank=True, null=True)),
                ('envolvido_id', models.IntegerField(blank=True, null=True)),
                ('envolvido_sexo', models.CharField(blank=True, max_length=1)),
                ('envolvido_idade', models.SmallIntegerField(blank=True, null=True)),
                ('envolvido_pele', models.CharField(blank=True, max_length=20)),
                ('envolvido_estatura', models.CharField(blank=True, max_length=10)),
                ('envolvido_porte', models.CharField(blank=True, max_length=10)),
                ('envolvido_cabelos', models.CharField(blank=True, max_length=40)),
                ('envolvido_olhos', models.CharField(blank=True, max_length=40)),
                ('envolvido_outras_caracteristicas', models.TextField(blank=True)),
                ('status_denuncia', models.CharField(blank=True, db_index=True, max_length=40)),
                ('relato_redacted', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['data_denuncia', 'classe'], name='ocorrencias_data_de_c395f7_idx'), models.Index(fields=['bairro_logradouro', 'classe'], name='ocorrencias_bairro__47610a_idx')],
            },
        ),
        migrations.CreateModel(
            name='FatorUrbano',
            fields=[
                ('id_resposta_ocorrencia', models.IntegerField(primary_key=True, serialize=False)),
                ('logradouro', models.CharField(blank=True, max_length=255)),
                ('numero_porta', models.CharField(blank=True, max_length=64)),
                ('referencia', models.CharField(blank=True, max_length=512)),
                ('observacao', models.TextField(blank=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('endereco_informado', models.BooleanField(blank=True, null=True)),
                ('valido', models.BooleanField(blank=True, null=True)),
                ('id_bairro', models.IntegerField(blank=True, null=True)),
                ('bairro_nome', models.CharField(blank=True, max_length=120)),
                ('id_subarea', models.IntegerField(blank=True, null=True)),
                ('subarea_nome', models.CharField(blank=True, max_length=255)),
                ('id_tipo_ocorrencia', models.SmallIntegerField(db_index=True)),
                ('tipo_ocorrencia_descricao', models.CharField(db_index=True, max_length=255)),
                ('tipo_ocorrencia_ativo', models.BooleanField(blank=True, null=True)),
                ('orgao_responsavel', models.CharField(blank=True, max_length=64)),
                ('id_orgao_ocorrencia', models.SmallIntegerField(blank=True, null=True)),
                ('ocorrencia_orgao_nome', models.CharField(blank=True, max_length=64)),
                ('codigo_ocorrencia_orgao', models.IntegerField(blank=True, null=True)),
                ('id_tipo_pessoa', models.SmallIntegerField(blank=True, null=True)),
                ('tipo_pessoa_descricao', models.CharField(blank=True, max_length=120)),
                ('id_ocupacao_pessoa', models.SmallIntegerField(blank=True, null=True)),
                ('ocupacao_pessoa_descricao', models.CharField(blank=True, max_length=120)),
                ('id_tipo_frequencia', models.SmallIntegerField(blank=True, null=True)),
                ('tipo_frequencia_descricao', models.CharField(blank=True, max_length=120)),
                ('ocupacao_drogas', models.SmallIntegerField(blank=True, null=True)),
                ('ocupacao_drogas_descricao', models.CharField(blank=True, max_length=120)),
                ('id_item_praca', models.SmallIntegerField(blank=True, null=True)),
                ('item_praca_descricao', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['id_tipo_ocorrencia', 'bairro_nome'], name='ocorrencias_id_tipo_ceb68c_idx'), models.Index(fields=['id_subarea'], name='ocorrencias_id_suba_8e7f2b_idx')],
            },
        ),
    ]
