# Generated by Django 6.0.5 on 2026-05-24 17:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0002_camera_diskdenuncia_fatorurbano'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaForca',
            fields=[
                ('fid', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_subar', models.CharField(db_index=True, max_length=255)),
                ('area_km2', models.FloatField()),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
