# Generated by Django 6.0.5 on 2026-05-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0003_areaforca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocorrencia',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='dia_semana',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='mes',
        ),
        # Make `data` non-null: drop any null rows first so the column can be
        # tightened. The loader now reconciles ano+mes into a never-null date,
        # so re-running `load_data --truncate --only ocorrencias` after this
        # migration restores those rows with synthetic day=1.
        migrations.RunSQL(
            "DELETE FROM ocorrencias_ocorrencia WHERE data IS NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data',
            field=models.DateField(db_index=True),
        ),
    ]
